"""Generate portable .sql files from the researched resort dataset.

Writes two dialects into <repo>/sql/:
  resorts_sqlite.sql  - matches app/schema.sql, loads with `sqlite3 file.db < ...`
  resorts_mysql.sql   - MySQL/MariaDB dialect, loads with `mysql db < ...`

Usage:  python scripts/export_sql.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db import RESORT_COLUMNS  # noqa: E402
from app.seed_data import RESORTS, TRIP  # noqa: E402

OUT_DIR = Path(__file__).resolve().parents[2] / "sql"

HEADER = f"""-- resort: candidate resorts for {TRIP["check_in"]} to {TRIP["check_out"]}
-- Party: {TRIP["adults"]} adults + {TRIP["children"]} child ({TRIP["nights"]} nights).
-- {TRIP["note"]}
--
-- Prices are SGD for the WHOLE PARTY per night and are indicative published or
-- average rates, NOT live quotes for these dates. Generated by
-- backend/scripts/export_sql.py -- edit app/seed_data.py and re-run instead of
-- editing this file by hand.
"""

SQLITE_DDL = """
DROP TABLE IF EXISTS trip;
CREATE TABLE trip (
    check_in   TEXT    NOT NULL,
    check_out  TEXT    NOT NULL,
    nights     INTEGER NOT NULL,
    adults     INTEGER NOT NULL,
    children   INTEGER NOT NULL,
    note       TEXT    NOT NULL
);

DROP TABLE IF EXISTS resorts;
CREATE TABLE resorts (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT    NOT NULL UNIQUE,
    destination   TEXT    NOT NULL,
    transport     TEXT    NOT NULL,
    travel_time   TEXT    NOT NULL,
    unit          TEXT    NOT NULL,
    bedrooms      INTEGER,
    one_unit      INTEGER NOT NULL DEFAULT 0,
    in_budget     INTEGER NOT NULL DEFAULT 1,
    nightly_low   INTEGER,
    nightly_high  INTEGER,
    review_score  REAL,
    review_scale  REAL,
    review_count  INTEGER,
    review_source TEXT,
    rank_note     TEXT,
    highlights    TEXT,
    watchouts     TEXT,
    price_note    TEXT
);
"""

MYSQL_DDL = """
DROP TABLE IF EXISTS `trip`;
CREATE TABLE `trip` (
    `check_in`  VARCHAR(10) NOT NULL,
    `check_out` VARCHAR(10) NOT NULL,
    `nights`    INT         NOT NULL,
    `adults`    INT         NOT NULL,
    `children`  INT         NOT NULL,
    `note`      TEXT        NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `resorts`;
CREATE TABLE `resorts` (
    `id`            INT AUTO_INCREMENT PRIMARY KEY,
    `name`          VARCHAR(191)  NOT NULL UNIQUE,
    `destination`   VARCHAR(64)   NOT NULL,
    `transport`     VARCHAR(32)   NOT NULL,
    `travel_time`   VARCHAR(96)   NOT NULL,
    `unit`          VARCHAR(191)  NOT NULL,
    `bedrooms`      INT           NULL,
    `one_unit`      TINYINT(1)    NOT NULL DEFAULT 0,
    `in_budget`     TINYINT(1)    NOT NULL DEFAULT 1,
    `nightly_low`   INT           NULL,
    `nightly_high`  INT           NULL,
    `review_score`  DECIMAL(3,1)  NULL,
    `review_scale`  DECIMAL(3,1)  NULL,
    `review_count`  INT           NULL,
    `review_source` VARCHAR(96)   NULL,
    `rank_note`     VARCHAR(191)  NULL,
    `highlights`    TEXT          NULL,
    `watchouts`     TEXT          NULL,
    `price_note`    TEXT          NULL,
    INDEX `idx_resorts_destination` (`destination`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""


def literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


TRIP_COLUMNS = ("check_in", "check_out", "nights", "adults", "children", "note")


def trip_row(quote: str) -> str:
    columns = ", ".join(f"{quote}{c}{quote}" for c in TRIP_COLUMNS)
    values = ", ".join(literal(TRIP.get(c)) for c in TRIP_COLUMNS)
    return f"INSERT INTO {quote}trip{quote} ({columns})\nVALUES ({values});"


def rows(quote: str) -> str:
    columns = ", ".join(f"{quote}{c}{quote}" for c in RESORT_COLUMNS)
    statements = []
    for resort in RESORTS:
        values = ", ".join(literal(resort.get(c)) for c in RESORT_COLUMNS)
        statements.append(f"INSERT INTO {quote}resorts{quote} ({columns})\nVALUES ({values});")
    return "\n\n".join(statements)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    sqlite_file = OUT_DIR / "resorts_sqlite.sql"
    sqlite_file.write_text(f"{HEADER}{SQLITE_DDL}\n{trip_row('')}\n\n{rows('')}\n")

    mysql_file = OUT_DIR / "resorts_mysql.sql"
    mysql_file.write_text(f"{HEADER}{MYSQL_DDL}\nSET NAMES utf8mb4;\n\n{rows('`')}\n")

    for path in (sqlite_file, mysql_file):
        print(f"wrote {path} ({path.stat().st_size:,} bytes, {len(RESORTS)} resorts)")


if __name__ == "__main__":
    main()
