"""Researched candidate resorts for the 7-9 Nov 2026 trip.

Party: 5 adults + one 5-year-old (6 people). No flights - ferry or car only.
Prices are SGD for the WHOLE PARTY per night and are indicative published /
average rates, NOT live quotes for 7-9 Nov 2026: the booking sites block
automated dated queries, and that weekend is the Deepavali long weekend
(Deepavali falls Sun 8 Nov 2026, holiday-in-lieu Mon 9 Nov), so expect a
long-weekend premium on top of these figures.
"""

TRIP = {
    "check_in": "2026-11-07",
    "check_out": "2026-11-09",
    "nights": 2,
    "adults": 5,
    "children": 1,
    "note": "Deepavali long weekend - Deepavali Sun 8 Nov 2026, holiday-in-lieu Mon 9 Nov.",
}

RESORTS = [
    {
        "name": "Nirwana Gardens - Indra Maya Pool Villa",
        "destination": "Bintan",
        "transport": "Ferry",
        "travel_time": "1h10m from Tanah Merah",
        "unit": "3-bedroom pool villa (sleeps 6)",
        "bedrooms": 3,
        "one_unit": 1,
        "in_budget": 1,
        "nightly_low": 800,
        "nightly_high": 800,
        "review_score": 4.0,
        "review_scale": 5.0,
        "review_count": 166,
        "review_source": "Tripadvisor",
        "rank_note": "#13 of 16 hotels in Lagoi",
        "highlights": "The only genuine 3-bedroom villa that lands inside budget. "
        "Private pool, 340-390 sqm, 4 bathrooms, own buggy, free ferry-terminal transfers, "
        "and access to all Nirwana Gardens facilities. Max occupancy 6 - fits the party exactly.",
        "watchouts": "Weakest ranking of the Bintan shortlist. Reviews repeatedly flag dated "
        "furniture, mosquitoes and limited dining outside peak hours. Occupancy 6 means zero slack.",
        "price_note": "S$800/night quoted for the 3-bedroom; property range S$302-763 for smaller units.",
    },
    {
        "name": "Nirwana Gardens - Banyu Biru Villa",
        "destination": "Bintan",
        "transport": "Ferry",
        "travel_time": "1h10m from Tanah Merah",
        "unit": "3-bedroom double-storey villa",
        "bedrooms": 3,
        "one_unit": 1,
        "in_budget": 1,
        "nightly_low": 450,
        "nightly_high": 700,
        "review_score": None,
        "review_scale": None,
        "review_count": None,
        "review_source": None,
        "rank_note": "Limited standalone review data",
        "highlights": "Cheapest true 3-bedroom single unit found. Double-storey villas with "
        "landscaped gardens, same Nirwana Gardens facilities and ferry shuttle as Indra Maya.",
        "watchouts": "Thin independent review coverage, and no private pool like Indra Maya. "
        "Rate band is an estimate - needs a direct quote to confirm.",
        "price_note": "Estimated band; one listing showed S$178 per person. Confirm with resort.",
    },
    {
        "name": "Banyan Tree Bintan",
        "destination": "Bintan",
        "transport": "Ferry",
        "travel_time": "1h10m from Tanah Merah",
        "unit": "2-bedroom Ocean Infinity Pool Villa (400 sqm) + 1 villa",
        "bedrooms": 2,
        "one_unit": 0,
        "in_budget": 1,
        "nightly_low": 900,
        "nightly_high": 1600,
        "review_score": 9.0,
        "review_scale": 10.0,
        "review_count": 140,
        "review_source": "Trip.com",
        "rank_note": "Best-reviewed property on the shortlist",
        "highlights": "Far and away the strongest reviews: 9.0/10 with service 9.1 and location 9.3. "
        "The 2-bedroom villa is a huge 400 sqm with private infinity pool.",
        "watchouts": "Tops out at 2 bedrooms - you would need a second villa, so not one unit. "
        "Most expensive in-budget option and skews couples/honeymoon rather than kids.",
        "price_note": "Villas from ~S$375/night; the 2-bedroom sits far above that. Estimated band.",
    },
    {
        "name": "Angsana Bintan (now Homm Laguna Bintan)",
        "destination": "Bintan",
        "transport": "Ferry",
        "travel_time": "1h10m from Tanah Merah",
        "unit": "2-bedroom Island Family Suite + 1 room",
        "bedrooms": 2,
        "one_unit": 0,
        "in_budget": 1,
        "nightly_low": 380,
        "nightly_high": 620,
        "review_score": 8.4,
        "review_scale": 10.0,
        "review_count": None,
        "review_source": "Booking.com / Expedia",
        "rank_note": "Rated 'Very good'",
        "highlights": "Family suites with two bedrooms, separate living and dining, private yard "
        "with outdoor jetpool. Kids club on site, private beach, free ferry transfer.",
        "watchouts": "2 bedrooms max, so a third room is needed. Recently rebranded to Homm Laguna "
        "Bintan - check which name your booking is under and whether service has settled.",
        "price_note": "Rooms from ~S$120-190/night; family suite plus a room is the estimated band.",
    },
    {
        "name": "Cassia Bintan",
        "destination": "Bintan",
        "transport": "Ferry",
        "travel_time": "1h10m from Tanah Merah",
        "unit": "2-bedroom apartment + 1-bedroom apartment",
        "bedrooms": 2,
        "one_unit": 0,
        "in_budget": 1,
        "nightly_low": 320,
        "nightly_high": 660,
        "review_score": 4.0,
        "review_scale": 5.0,
        "review_count": 2388,
        "review_source": "Tripadvisor",
        "rank_note": "#1 of 53 hotels in Bintan Island/Lagoi",
        "highlights": "Best value-for-reviews on the board: ranked #1 in Lagoi off 2,388 reviews. "
        "Self-catering apartments with kitchens - useful with a 5-year-old. Same Banyan Group beach.",
        "watchouts": "1 and 2 bedroom units only, so the party needs two apartments. "
        "Apartment blocks rather than a villa experience.",
        "price_note": "USD 120-250 per apartment per night, plus 10% service and 11% tax. Converted at ~1.3.",
    },
    {
        "name": "The Sanchaya",
        "destination": "Bintan",
        "transport": "Ferry",
        "travel_time": "1h10m from Tanah Merah",
        "unit": "3-bedroom villa (13 villas, 1-4 bedrooms)",
        "bedrooms": 3,
        "one_unit": 1,
        "in_budget": 0,
        "nightly_low": 3000,
        "nightly_high": 6000,
        "review_score": None,
        "review_scale": None,
        "review_count": None,
        "review_source": None,
        "rank_note": "Ultra-luxury reference point",
        "highlights": "The most beautiful property in Bintan by reputation - colonial-estate styling, "
        "3-bedroom villas genuinely available.",
        "watchouts": "Way over budget. Its 4-bedroom Vanda Villa lists at USD 10,000 a night, "
        "which sets the tone for the 3-bedroom.",
        "price_note": "Estimated from the published USD 10,000 four-bedroom rate. Included for context only.",
    },
    {
        "name": "Montigo Resorts Nongsa",
        "destination": "Batam",
        "transport": "Ferry",
        "travel_time": "~50m from Harbourfront/Tanah Merah",
        "unit": "4-bedroom Montigo Residence (no 3-bedroom exists)",
        "bedrooms": 4,
        "one_unit": 1,
        "in_budget": 1,
        "nightly_low": 700,
        "nightly_high": 1300,
        "review_score": 4.0,
        "review_scale": 5.0,
        "review_count": 5363,
        "review_source": "Tripadvisor",
        "rank_note": "#14 of 144 hotels in Batam",
        "highlights": "Closest ferry hop and the biggest review sample on the board (5,363). "
        "Villas have private plunge pools; the 4-bedroom Residence adds a personal butler. "
        "Popular precisely because it is the easy Singapore weekend trip.",
        "watchouts": "Inventory jumps 2-bedroom straight to 4-bedroom - there is no 3-bedroom, so "
        "you pay for a spare room. Reviews are mixed on maintenance and cleanliness.",
        "price_note": "Resort from ~S$145-190/night for studios; 4-bedroom Residence band is estimated.",
    },
    {
        "name": "Turi Beach Resort",
        "destination": "Batam",
        "transport": "Ferry",
        "travel_time": "~50m from Harbourfront",
        "unit": "3 rooms",
        "bedrooms": None,
        "one_unit": 0,
        "in_budget": 1,
        "nightly_low": 180,
        "nightly_high": 270,
        "review_score": 8.0,
        "review_scale": 10.0,
        "review_count": 2296,
        "review_source": "Kayak (Tripadvisor 3/5)",
        "rank_note": "#27 of 144 hotels in Batam",
        "highlights": "By far the cheapest credible option - three rooms for roughly the price of "
        "one villa bedroom elsewhere. Beachfront at Nongsa, multiple pools, staff well reviewed.",
        "watchouts": "Only 3 of 5 on Tripadvisor. Recurring complaints about beach cleanliness and "
        "expensive food and drink. Rooms, not a villa - no shared living space for the group.",
        "price_note": "~S$60-90 per room per night, x3 rooms.",
    },
    {
        "name": "HARRIS Resort Barelang",
        "destination": "Batam",
        "transport": "Ferry",
        "travel_time": "~50m ferry + ~40m land transfer",
        "unit": "3 rooms / family villas",
        "bedrooms": None,
        "one_unit": 0,
        "in_budget": 1,
        "nightly_low": 210,
        "nightly_high": 330,
        "review_score": None,
        "review_scale": None,
        "review_count": None,
        "review_source": None,
        "rank_note": "4-star, family positioned",
        "highlights": "Strong kid infrastructure - infinity pool plus a dedicated kids pool. "
        "Cheap, and explicitly family oriented.",
        "watchouts": "20 km out from the city with a long land transfer after the ferry, which is a "
        "real cost with a 5-year-old. Sparse independent review data.",
        "price_note": "From ~S$70 per room per night, x3 rooms.",
    },
    {
        "name": "Anantara Desaru Coast Resort & Villas",
        "destination": "Desaru, Johor",
        "transport": "Car",
        "travel_time": "2-3h via Tuas Second Link",
        "unit": "3-bedroom Residence (garden + infinity pool)",
        "bedrooms": 3,
        "one_unit": 1,
        "in_budget": 1,
        "nightly_low": 1500,
        "nightly_high": 2500,
        "review_score": None,
        "review_scale": None,
        "review_count": 518,
        "review_source": "Tripadvisor (518 reviews, family-positive)",
        "rank_note": "Strongest family reviews in Desaru",
        "highlights": "A real 3-bedroom single unit with its own garden and infinity pool, private "
        "chef and butler. Kids club is the single most praised feature across its reviews, plus a "
        "teens club, two pools, free bicycles and outdoor movie nights. Baby gear provided on request.",
        "watchouts": "Top of or above budget. Needs a car: VEP has been mandatory since July 2025, "
        "and Saturday-morning Tuas queues on a long weekend can turn the drive into 3-4 hours.",
        "price_note": "Rate not published; band estimated from Anantara residence positioning. Get a direct quote.",
    },
    {
        "name": "The Westin Desaru Coast Resort",
        "destination": "Desaru, Johor",
        "transport": "Car",
        "travel_time": "2-3h via Tuas Second Link",
        "unit": "3 rooms (no villas)",
        "bedrooms": None,
        "one_unit": 0,
        "in_budget": 1,
        "nightly_low": 570,
        "nightly_high": 870,
        "review_score": None,
        "review_scale": None,
        "review_count": None,
        "review_source": "Tripadvisor / Kayak",
        "rank_note": "Mixed value perception",
        "highlights": "Spacious rooms, praised cleanliness, good beach access and a diverse set of pools.",
        "watchouts": "Rooms only - no villa, so no single unit. Several reviewers call it overpriced "
        "and note a gap in luxury feel and service versus neighbours.",
        "price_note": "From ~S$190-290 per room per night, x3 rooms.",
    },
    {
        "name": "Hard Rock Hotel Desaru Coast",
        "destination": "Desaru, Johor",
        "transport": "Car",
        "travel_time": "2-3h via Tuas Second Link",
        "unit": "Family connecting rooms x3",
        "bedrooms": None,
        "one_unit": 0,
        "in_budget": 1,
        "nightly_low": 420,
        "nightly_high": 750,
        "review_score": 8.6,
        "review_scale": 10.0,
        "review_count": None,
        "review_source": "Tripadvisor / Booking.com",
        "rank_note": "#1 of 11 hotels in Bandar Penawar",
        "highlights": "Best-rated property in Desaru and the most kid-focused on the whole board: "
        "direct access to the Desaru Coast Adventure Waterpark, heavily praised kids club, "
        "connecting family rooms, free buffet breakfast.",
        "watchouts": "Connecting rooms rather than a villa. Requires the car + VEP drive, and it is "
        "the loud, busy, theme-park end of the market rather than a quiet resort.",
        "price_note": "~S$140-250 per room per night, x3 rooms.",
    },
]
