-- resort: candidate resorts for 2026-11-07 to 2026-11-09
-- Party: 5 adults + 1 child (2 nights).
-- Deepavali long weekend - Deepavali Sun 8 Nov 2026, holiday-in-lieu Mon 9 Nov.
--
-- Prices are SGD for the WHOLE PARTY per night and are indicative published or
-- average rates, NOT live quotes for these dates. Generated by
-- backend/scripts/export_sql.py -- edit app/seed_data.py and re-run instead of
-- editing this file by hand.

DROP TABLE IF EXISTS `trip`;
CREATE TABLE `trip` (
    `check_in`  VARCHAR(10) NOT NULL,
    `check_out` VARCHAR(10) NOT NULL,
    `nights`    INT         NOT NULL,
    `adults`    INT         NOT NULL,
    `children`  INT         NOT NULL,
    `note`      TEXT        NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `resorts`;
CREATE TABLE `resorts` (
    `id`            INT AUTO_INCREMENT PRIMARY KEY,
    `name`          VARCHAR(191)  NOT NULL UNIQUE,
    `destination`   VARCHAR(64)   NOT NULL,
    `transport`     VARCHAR(32)   NOT NULL,
    `travel_time`   VARCHAR(96)   NOT NULL,
    `unit`          VARCHAR(191)  NOT NULL,
    `bedrooms`      INT           NULL,
    `one_unit`      TINYINT(1)    NOT NULL DEFAULT 0,
    `in_budget`     TINYINT(1)    NOT NULL DEFAULT 1,
    `nightly_low`   INT           NULL,
    `nightly_high`  INT           NULL,
    `review_score`  DECIMAL(3,1)  NULL,
    `review_scale`  DECIMAL(3,1)  NULL,
    `review_count`  INT           NULL,
    `review_source` VARCHAR(96)   NULL,
    `rank_note`     VARCHAR(191)  NULL,
    `highlights`    TEXT          NULL,
    `watchouts`     TEXT          NULL,
    `price_note`    TEXT          NULL,
    INDEX `idx_resorts_destination` (`destination`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET NAMES utf8mb4;

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Nirwana Gardens - Indra Maya Pool Villa', 'Bintan', 'Ferry', '1h10m from Tanah Merah', '3-bedroom pool villa (sleeps 6)', 3, 1, 1, 800, 800, 4.0, 5.0, 166, 'Tripadvisor', '#13 of 16 hotels in Lagoi', 'The only genuine 3-bedroom villa that lands inside budget. Private pool, 340-390 sqm, 4 bathrooms, own buggy, free ferry-terminal transfers, and access to all Nirwana Gardens facilities. Max occupancy 6 - fits the party exactly.', 'Weakest ranking of the Bintan shortlist. Reviews repeatedly flag dated furniture, mosquitoes and limited dining outside peak hours. Occupancy 6 means zero slack.', 'S$800/night quoted for the 3-bedroom; property range S$302-763 for smaller units.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Nirwana Gardens - Banyu Biru Villa', 'Bintan', 'Ferry', '1h10m from Tanah Merah', '3-bedroom double-storey villa', 3, 1, 1, 450, 700, NULL, NULL, NULL, NULL, 'Limited standalone review data', 'Cheapest true 3-bedroom single unit found. Double-storey villas with landscaped gardens, same Nirwana Gardens facilities and ferry shuttle as Indra Maya.', 'Thin independent review coverage, and no private pool like Indra Maya. Rate band is an estimate - needs a direct quote to confirm.', 'Estimated band; one listing showed S$178 per person. Confirm with resort.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Banyan Tree Bintan', 'Bintan', 'Ferry', '1h10m from Tanah Merah', '2-bedroom Ocean Infinity Pool Villa (400 sqm) + 1 villa', 2, 0, 1, 900, 1600, 9.0, 10.0, 140, 'Trip.com', 'Best-reviewed property on the shortlist', 'Far and away the strongest reviews: 9.0/10 with service 9.1 and location 9.3. The 2-bedroom villa is a huge 400 sqm with private infinity pool.', 'Tops out at 2 bedrooms - you would need a second villa, so not one unit. Most expensive in-budget option and skews couples/honeymoon rather than kids.', 'Villas from ~S$375/night; the 2-bedroom sits far above that. Estimated band.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Angsana Bintan (now Homm Laguna Bintan)', 'Bintan', 'Ferry', '1h10m from Tanah Merah', '2-bedroom Island Family Suite + 1 room', 2, 0, 1, 380, 620, 8.4, 10.0, NULL, 'Booking.com / Expedia', 'Rated ''Very good''', 'Family suites with two bedrooms, separate living and dining, private yard with outdoor jetpool. Kids club on site, private beach, free ferry transfer.', '2 bedrooms max, so a third room is needed. Recently rebranded to Homm Laguna Bintan - check which name your booking is under and whether service has settled.', 'Rooms from ~S$120-190/night; family suite plus a room is the estimated band.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Cassia Bintan', 'Bintan', 'Ferry', '1h10m from Tanah Merah', '2-bedroom apartment + 1-bedroom apartment', 2, 0, 1, 320, 660, 4.0, 5.0, 2388, 'Tripadvisor', '#1 of 53 hotels in Bintan Island/Lagoi', 'Best value-for-reviews on the board: ranked #1 in Lagoi off 2,388 reviews. Self-catering apartments with kitchens - useful with a 5-year-old. Same Banyan Group beach.', '1 and 2 bedroom units only, so the party needs two apartments. Apartment blocks rather than a villa experience.', 'USD 120-250 per apartment per night, plus 10% service and 11% tax. Converted at ~1.3.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('The Sanchaya', 'Bintan', 'Ferry', '1h10m from Tanah Merah', '3-bedroom villa (13 villas, 1-4 bedrooms)', 3, 1, 0, 3000, 6000, NULL, NULL, NULL, NULL, 'Ultra-luxury reference point', 'The most beautiful property in Bintan by reputation - colonial-estate styling, 3-bedroom villas genuinely available.', 'Way over budget. Its 4-bedroom Vanda Villa lists at USD 10,000 a night, which sets the tone for the 3-bedroom.', 'Estimated from the published USD 10,000 four-bedroom rate. Included for context only.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Montigo Resorts Nongsa', 'Batam', 'Ferry', '~50m from Harbourfront/Tanah Merah', '4-bedroom Montigo Residence (no 3-bedroom exists)', 4, 1, 1, 700, 1300, 4.0, 5.0, 5363, 'Tripadvisor', '#14 of 144 hotels in Batam', 'Closest ferry hop and the biggest review sample on the board (5,363). Villas have private plunge pools; the 4-bedroom Residence adds a personal butler. Popular precisely because it is the easy Singapore weekend trip.', 'Inventory jumps 2-bedroom straight to 4-bedroom - there is no 3-bedroom, so you pay for a spare room. Reviews are mixed on maintenance and cleanliness.', 'Resort from ~S$145-190/night for studios; 4-bedroom Residence band is estimated.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Turi Beach Resort', 'Batam', 'Ferry', '~50m from Harbourfront', '3 rooms', NULL, 0, 1, 180, 270, 8.0, 10.0, 2296, 'Kayak (Tripadvisor 3/5)', '#27 of 144 hotels in Batam', 'By far the cheapest credible option - three rooms for roughly the price of one villa bedroom elsewhere. Beachfront at Nongsa, multiple pools, staff well reviewed.', 'Only 3 of 5 on Tripadvisor. Recurring complaints about beach cleanliness and expensive food and drink. Rooms, not a villa - no shared living space for the group.', '~S$60-90 per room per night, x3 rooms.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('HARRIS Resort Barelang', 'Batam', 'Ferry', '~50m ferry + ~40m land transfer', '3 rooms / family villas', NULL, 0, 1, 210, 330, NULL, NULL, NULL, NULL, '4-star, family positioned', 'Strong kid infrastructure - infinity pool plus a dedicated kids pool. Cheap, and explicitly family oriented.', '20 km out from the city with a long land transfer after the ferry, which is a real cost with a 5-year-old. Sparse independent review data.', 'From ~S$70 per room per night, x3 rooms.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Anantara Desaru Coast Resort & Villas', 'Desaru, Johor', 'Car', '2-3h via Tuas Second Link', '3-bedroom Residence (garden + infinity pool)', 3, 1, 1, 1500, 2500, NULL, NULL, 518, 'Tripadvisor (518 reviews, family-positive)', 'Strongest family reviews in Desaru', 'A real 3-bedroom single unit with its own garden and infinity pool, private chef and butler. Kids club is the single most praised feature across its reviews, plus a teens club, two pools, free bicycles and outdoor movie nights. Baby gear provided on request.', 'Top of or above budget. Needs a car: VEP has been mandatory since July 2025, and Saturday-morning Tuas queues on a long weekend can turn the drive into 3-4 hours.', 'Rate not published; band estimated from Anantara residence positioning. Get a direct quote.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('The Westin Desaru Coast Resort', 'Desaru, Johor', 'Car', '2-3h via Tuas Second Link', '3 rooms (no villas)', NULL, 0, 1, 570, 870, NULL, NULL, NULL, 'Tripadvisor / Kayak', 'Mixed value perception', 'Spacious rooms, praised cleanliness, good beach access and a diverse set of pools.', 'Rooms only - no villa, so no single unit. Several reviewers call it overpriced and note a gap in luxury feel and service versus neighbours.', 'From ~S$190-290 per room per night, x3 rooms.');

INSERT INTO `resorts` (`name`, `destination`, `transport`, `travel_time`, `unit`, `bedrooms`, `one_unit`, `in_budget`, `nightly_low`, `nightly_high`, `review_score`, `review_scale`, `review_count`, `review_source`, `rank_note`, `highlights`, `watchouts`, `price_note`)
VALUES ('Hard Rock Hotel Desaru Coast', 'Desaru, Johor', 'Car', '2-3h via Tuas Second Link', 'Family connecting rooms x3', NULL, 0, 1, 420, 750, 8.6, 10.0, NULL, 'Tripadvisor / Booking.com', '#1 of 11 hotels in Bandar Penawar', 'Best-rated property in Desaru and the most kid-focused on the whole board: direct access to the Desaru Coast Adventure Waterpark, heavily praised kids club, connecting family rooms, free buffet breakfast.', 'Connecting rooms rather than a villa. Requires the car + VEP drive, and it is the loud, busy, theme-park end of the market rather than a quiet resort.', '~S$140-250 per room per night, x3 rooms.');
